# Generated by Django 2.1.2 on 2019-10-22 21:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Movies', '0013_auto_20190221_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Watched',
        ),
        migrations.AddField(
            model_name='ratings',
            name='Movie',
            field=models.ForeignKey(on_delete=models.CASCADE, to='Movies.Movie'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='User',
            field=models.ForeignKey(on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
